---

# Our api_groups variable may be expected in our template files.
# It's used to dynamically reconfigure the kubernetes objects
# mainly based on whether we're deploying to native Kubernetes
# or OpensShift.

- name: Get information about the cluster
  set_fact:
    api_groups: "{{ lookup('k8s', cluster_info='api_groups') }}"

- name: Set objects state={{ state }}
  k8s:
    state: '{{ state }}'
    definition: "{{ lookup('template', item.name)|from_yaml }}"
  loop:
    - name: deployment.yml.j2
    - name: service.yml.j2
